version: '3'
services:

  db1:
    container_name: $DB_NAME_1
    image: mariadb:10.9.2
    env_file:
      - ./db1/env/.env
    volumes:
      - './db1/data:/var/lib/mysql'
      - './db1/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf'
    ports:
      - "3301:3306"
    networks:
      db-stack:
        ipv4_address: 10.10.0.101

  db2:
    container_name: $DB_NAME_2
    image: mariadb:10.9.2
    env_file:
      - ./db2/env/.env
    volumes:
      - './db2/data:/var/lib/mysql'
      - './db2/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf'
    ports:
      - "3302:3306"
    networks:
      db-stack:
        ipv4_address: 10.10.0.102

networks:
  db-stack:
    driver: bridge
    ipam:
     config:
       - subnet: 10.10.0.0/16
         gateway: 10.10.0.1